### PR TITLE
Change to require a Signer so that it can be used with external wallets such as metamask

### PR DESCRIPTION
**Pull request by serinuntius**

### CODE REVIEW

**Comment by hazim-j** [comment]
Thanks for the PR @serinuntius. Do you have an example of where this is an issue? Or give more context on how you are using this with external wallets?

**Comment by serinuntius** [comment]
Thanks for the reply @hazim-j . For example the following pattern.

ex) React
```ts
import { useContract, useSigner } from 'wagmi'
 
function App() {
  const { data: signer, isError, isLoading } = useSigner();
  
  const handler = async () => {
     // metamask provides a signer but not a signingKey.
     const simpleAccount = await SimpleAccount.init(signer, bundler, entryPoint, factory);
  }
}
```

**Comment by hazim-j** [comment]
This makes sense! I will test this out and merge when we do the next release for userop.js

**Comment by serinuntius** [comment]
Great! Thank you!

**Pull request merged**
